Energy_Balance_ERA5_GIS:
  module: lex/energy/energy.py
  references: [/global/cfs/cdirs/e3sm/livvkit/data/racmo/Noel2015.bib,/global/cfs/cdirs/e3sm/livvkit/data/cism/glissade/cism-glissade.bib,/global/cfs/cdirs/e3sm/livvkit/data/e3sm/Evans2019.bib,
   /global/cfs/cdirs/e3sm/livvkit/data/livvkit.bib]
  meta:
    Case ID: [CASE_ID]
    Climatology years: [1980-2020]
    Model: [E3SM-ELM]
  img_height: 300
  climo: /pscratch/sd/m/mek/lex/data/e3sm/CASE_ID/CASE_ID.{clim}_mean.nc
  climo_remap: /pscratch/sd/m/mek/lex/data/e3sm/CASE_ID/remap/CASE_ID.{clim}_mean_era5.nc
  lnd_climo: /pscratch/sd/m/mek/lex/data/e3sm/CASE_ID/remap/CASE_ID.ANN_mean_era5.nc
  glc_surf: /pscratch/sd/m/mek/lex/data/e3sm/CASE_ID/remap/CASE_ID.ANN_mean_era5.nc
  
  latlon: /pscratch/sd/m/mek/lex/data/e3sm/CASE_ID/remap/CASE_ID.ANN_mean_era5.nc
  elevation: /pscratch/sd/m/mek/lex/data/e3sm/CASE_ID/remap/CASE_ID.ANN_mean_era5.nc
  latv: lat
  lonv: lon
  topov: topo
  landfracv: landfrac
  mask_ocean: {model_native: false, model_remap: true, dset_a: true}
  maskv: gis_mask2
  dataset_names: {model_remap: 'ELM [ERA5 Grid]', model_native: ELM, dset_a: ERA5}
  aavg_sort: [ELM, 'ELM [ERA5 Grid]', ERA5]
  scales: {model: 1, dset_a: 1}
  clim_years:
    dset_a: { year_s: 1979, year_e: 2019}
  data_vars:
  - dset_a: ts
    dset_b: TSA
    model: TSA
    title: Surface temperature
    sign: 1
    scales: {dset_a: 1, dset_b: 1, model: 1}
    units: K
  - title: Albedo
    dset_a: [/, rsus, rsds]
    model:
    - /
    - [+, FSRND, FSRVD]
    - [+, FSDSVD, FSDSND]
    sign: 1
    scales: {dset_a: 1, model: 1}
    units: unitless
    cmin: 0.5
    cmax: 1.0
    cmin_d: -0.2
    cmax_d: 0.2
  - dset_a: ['-', rsds, rsus]
    model: FSA
    title: Shortwave net
    comment: ' (Positive to surface)'
    sign: 1
    scales: {dset_a: 1, model: 1}
    units: W m^-2
  - dset_a: rsds
    model: FSDS
    title: Shortwave down
    sign: 1
    scales: {dset_a: 1, model: 1}
    units: W m^-2
  - dset_a: ['-', rlus, rlds]
    model: FIRA
    title: Longwave net
    comment: ' (Positive to atmosphere)'
    sign: 1
    scales: {dset_a: 1, model: 1}
    units: W m^-2
  - dset_a: rlds
    model: FLDS
    title: Longwave down
    sign: 1
    scales: {dset_a: 1, model: 1}
    units: W m^-2
  - dset_a: hfss
    dset_b: FSH
    model: FSH
    title: Sensible heat
    comment: ' (Positive to atmosphere)'
    sign: 1
    scales: {dset_a: 1, dset_b: 1, model: 1}
    units: W m^-2
  - dset_a: hfls
    dset_b: EFLX_LH_TOT
    model: EFLX_LH_TOT
    title: Latent Heat Flux
    comment: ' (Positive to atmosphere)'
    sign: 1
    scales: {dset_a: 1, dset_b: 1, model: 1}
    units: W m^-2
  - title: Net energy balance
    dset_a:
    - '-'
    - ['-', rsds, rsus]
    - - +
      - ['-', rlus, rlds]
      - [+, hfss, hfls]
    model:
    - '-'
    - FSA
    - - +
      - FIRA
      - [+, FSH, EFLX_LH_TOT]
    sign: 1
    scales: {dset_a: 1, dset_b: 1, model: 1}
    units: W m^-2
    cmin: -10
    cmax: 10
    cmap: RdBu_r
  in_dirs: {dset_a: /global/cfs/cdirs/e3sm/e3sm_diags/obs_for_e3sm_diags/climatology/ERA5}
  file_patterns: {dset_a: 'ERA5_{season}_{sea_s}_{sea_e}_climo.nc'}
  masks: {
    dset_a: /global/cfs/cdirs/e3sm/livvkit/grids/msk_gis_rcm_r025_regrid_era5_traave_20250213.nc,
    model_remap: /global/cfs/cdirs/e3sm/livvkit/grids/msk_gis_rcm_r025_regrid_era5_traave_20250213.nc,
    model_native: /global/cfs/cdirs/e3sm/livvkit/grids/msk_gis_rcm_r05.nc
  }
  desc: Surface energy balance component {component}{comment} from {data_var_names}
  cmap: plasma
  cmap_diff: RdBu_r
